services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: mediacontent
      MONGO_INITDB_ROOT_USERNAME: alejandro-mediacontent
      MONGO_INITDB_ROOT_PASSWORD: alejandro-mediacontent
    volumes:
      - ./mongo:/data/db
